package com.emc.ocopea.messaging;

/**
 * Exception wrappers generated by the shpan messaging library
 */
public class PersistentMessagingException extends RuntimeException {
    public PersistentMessagingException(String message) {
        super(message);
    }

    public PersistentMessagingException(String message, Throwable cause) {
        super(message, cause);
    }
}
